name: employeemanager
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  # flutter_localizations:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  cloud_firestore: ^4.16.0
  image_cropper: ^1.5.1
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  flutter_image_compress: ^2.1.0
  firebase_storage: ^11.7.1
  uuid: ^4.4.0
  another_flutter_splash_screen: ^1.2.0
  go_router: ^13.2.4
  country_code_picker: ^3.0.0
  flutter_libphonenumber: ^2.2.3
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_date_pickers: ^0.4.3
  date_picker_plus: ^4.1.0
  pdf: ^3.10.6
  printing: ^5.12.0
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1 # dart run build_runner build --delete-conflicting-outputs

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/